version: '3.8'

services:
  frontend:
    image: nginx:alpine
    container_name: catsup_frontend_temporal
    restart: always

  gallery:
    build:
      context: ./gallery
      dockerfile: gallery.dockerfile
    container_name: catsup_gallery
    restart: always
    ports:
      - "8002:8000"
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - SECRET_KEY=clave_secreta_de_produccion
      - DEBUG=True
      - USE_S3=False
  
  login:
    build:
      context: ./login
      dockerfile: login.dockerfile
    container_name: catsup_login
    restart: always
    ports:
      - "8001:8000"
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - SECRET_KEY=clave_secreta_de_produccion
      - DEBUG=True
      - USE_S3=False

  ranking:
    build:
      context: ./ranking
      dockerfile: ranking.dockerfile
    container_name: catsup_ranking
    restart: always
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - SECRET_KEY=clave_secreta_de_produccion
      - DEBUG=True
      - USE_S3=False

  comentarios:
    build:
      context: ./comentarios
      dockerfile: comentarios.dockerfile
    container_name: catsup_comentarios
    restart: always
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - SECRET_KEY=clave_secreta_de_produccion
      - DEBUG=True
      - USE_S3=False

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - gallery
      - login
      - ranking
      - comentarios