version: '3.8'

services:
  frontend:
    image: niquinpro1/catsup-frontend:latest
    restart: always

  gallery:  
    image: niquinpro1/catsup-gallery:latest
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - SECRET_KEY=clave_secreta_de_produccion
      - DEBUG=True
      - USE_S3=False
    restart: always

  login:
    image: niquinpro1/catsup-login:latest
    restart: always
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - SECRET_KEY=clave_secreta_de_produccion
      - DEBUG=True
      - USE_S3=False

  ranking:
    image: niquinpro1/catsup-ranking:latest
    restart: always
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - SECRET_KEY=clave_secreta_de_produccion
      - DEBUG=True
      - USE_S3=False

  comentarios:
    image: niquinpro1/catsup-comentarios:latest
    restart: always
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - SECRET_KEY=clave_secreta_de_produccion
      - DEBUG=True
      - USE_S3=False

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - gallery
      - login
      - ranking