# Generated by Django 6.0.6 on 2026-06-28 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0003_remove_post_image_url_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('gato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='gallery.catprofile')),
            ],
        ),
    ]
