version: '3.8'

services:
  backend:
    image: niquinpro1/catsup-backend:lastest
    ports:
      - "8000:8000"
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - SECRET_KEY=clave_secreta_de_produccion
      - DEBUG=True
      - USE_S3=False
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend