server {
    listen 80;
    location / {
        proxy_pass http://frontend:8000;
    }
    location /api/login {
        proxy_pass http://login:8000;
    }
    location /api/rankings {
        proxy_pass http://<DNS_O_IP_DEL_AZURE_LOAD_BALANCER_11>:8000;
    }
    location /api/multimedia {
        proxy_pass http://<DNS_O_IP_DEL_AZURE_LOAD_BALANCER_11>:8000;
    }
    location /api/comentarios {
        proxy_pass http://<DNS_O_IP_DEL_AZURE_LOAD_BALANCER_11>:8000;
    }
}