server {
    listen 80;
    server_name tu-dominio.com;
    return 301 [https://catsup.servemp3.com](https://catsup.servemp3.com)$request_uri;
}

server {
    listen 443 ssl;
    server_name catsup.servemp3.com;

    ssl_certificate /etc/letsencrypt/live/catsup.servemp3/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/catsup.servemp3/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    set $cors_origin "https://catsup.servemp3.com";

    location /api/ranking/ {
        proxy_pass http://<IP_O_LB_AWS>:8002;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' $cors_origin always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE';
            add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type, X-Requested-With';
            add_header 'Access-Control-Max-Age' 1728000;
            return 204;
        }
    }

    location /api/comentarios/ {
        proxy_pass http://<IP_O_LB_AZURE>:8003;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' $cors_origin always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE';
            add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type, X-Requested-With';
            add_header 'Access-Control-Max-Age' 1728000;
            return 204;
        }
    }

    location / {
        proxy_pass http://<IP_O_LB_AWS>:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}