map $http_origin $cors_origin {
    default "https://catsup.servemp3.com";
}

server {
    listen 80;
    server_name catsup.servemp3.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name catsup.servemp3.com;

    ssl_certificate /etc/letsencrypt/live/catsup.servemp3/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/catsup.servemp3/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' $cors_origin always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE';
        add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type, X-Requested-With';
        add_header 'Access-Control-Max-Age' 1728000;
        return 204;
    }

    location /api/auth/ {
        proxy_pass http://<IP_O_LB_LOGIN>:8000; 
    }

    location /api/multimedia/ {
        proxy_pass http://<IP_O_LB_MULTIMEDIA>:8000;
    }

    # Comentarios (Ya definido anteriormente)
    location /api/comentarios/ {
        proxy_pass http://<IP_O_LB_AZURE>:8003;
    }

    # Ranking (Ya definido anteriormente)
    location /api/ranking/ {
        proxy_pass http://<IP_O_LB_AWS>:8002;
    }

    # Ruta por defecto (Frontend o raíz)
    location / {
        proxy_pass http://<IP_O_LB_AWS>:80;
    }
}