---
- name: Instalar Docker y clonar Microservicio en AWS
  hosts: app_servers
  become: true
  tasks:
    - name: 1. Actualizar el sistema (apt-get update)
      apt:
        update_cache: true
        force_apt_get: true
    - name: 2. instalar herramientas Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
    - name: 3. Agregar la clave oficial de Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: 4. Agregar el repositorio oficial de Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: 5. Instalar Docker
      apt:
        name: 
          - docker-ce
          - docker-compose-plugin
        state: present

    - name: 6. Asegurar que Docker este encendido y activo
      service:
        name: docker
        state: started
        enabled: true
    - name: 7. crear la carpeta del proyecto
      file:
        path: /home/ubuntu/app
        state: directory
        mode: '0755'
    - name: 8. copiar el archivo default.conf de Nginx
      copy:
        src: ../nginx/default.conf
        dest: /home/ubuntu/app/default.conf
        mode: '0644'
    - name: 9. copiar el docker-compose
      template:
        src: ../docker-compose-aws.yml
        dest: /home/ubuntu/docker-compose-aws.yml
        mode: '0644'
    - name: 10. decargar imagenes y levantar
      command: docker compose up -d
      args:
        chdir: /home/ubuntu/app
    - name: 11. Ejecutar las migraciones del modulo gallery
      command: docker exec app_gallery_1 python manage.py migrate
      run_once: true
    - name: 12. Ejecutar las migraciones del modulo login
      command: docker exec app_login_1 python manage.py migrate
      run_once: true
    - name: 13. Ejecutar las migraciones en el modulo ranking
      command: docker exec app_ranking_1 python manage.py migrate
      run_once: true